@ContactsApi.Api_HostAddress = http://localhost:5181

GET {{ContactsApi.Api_HostAddress}}/todos/
Accept: application/json

###

GET {{ContactsApi.Api_HostAddress}}/todos/1
Accept: application/json

###
